/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2013-06-14 08:15:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.actions;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class pi_005faction_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      server.boundary.TCPclientCommandBean piControl = null;
      piControl = (server.boundary.TCPclientCommandBean) _jspx_page_context.getAttribute("piControl", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (piControl == null){
        piControl = new server.boundary.TCPclientCommandBean();
        _jspx_page_context.setAttribute("piControl", piControl, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\n');
      out.write('\n');
  
    String[] availibleActions = {"Start", "Stop", "Get WiFi status", "Scan networks", "Set channel"};
    
    String selectedPi, action, output;
    
    /* Get post values */
    selectedPi = request.getParameter("selectedPi");
    action = request.getParameter("action");
    
    /* Insert requested action in output string */
    output = "Action, '" + action + "' returned: ";
    
    /* Select the correct action to perform */
    try {
        if(availibleActions[0].equals(action)) {
            piControl.startUDPSocket(selectedPi);
            output = output + "OK";
        }
        else if (availibleActions[1].equals(action)) {
            piControl.stopUDPSocket(selectedPi);
            output = output + "OK";
        }
        else if (availibleActions[2].equals(action)) {
            output = output + piControl.getWifiStatus(selectedPi);
        }
        else if (availibleActions[3].equals(action)) {
            output = output + piControl.scanNetworks(selectedPi);
        }
        else if (availibleActions[4].equals(action)) {
            piControl.setChannel(selectedPi, 1);
            output = output + "OK";
        }
    }
    catch (Exception e) {
        output = output + "Error";
    }
    
    session.setAttribute("pi_response", output);

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <title>Network Monitoring System - Saving data...</title>\n");
      out.write("        <meta http-equiv=\"refresh\" content=\"0; url=../pi_control.jsp\">\n");
      out.write("    </head>\n");
      out.write("    \n");
      out.write("    <body>\n");
      out.write("        ");
 out.println(output); 
      out.write("\n");
      out.write("        See the result <a href=\"./pi_control.jsp\">here.</a>\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
