/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.41
 * Generated at: 2013-06-13 14:08:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class statistics_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/./includes/bottom.jsp", Long.valueOf(1371125968098L));
    _jspx_dependants.put("/./includes/top.jsp", Long.valueOf(1371125968099L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


    String pageName, pageNameNice;
    int position;
    
    /* Gets the name of the current file */
    pageName = request.getRequestURI();
    position = pageName.lastIndexOf("/");
    pageName = pageName.substring(position+1);
    
    /* If there is no filename, it must be because we are on the home-page */
    if(pageName.length() < 4) {
        pageName = "home.jsp";
    }
    
    /* Generates a nice looking pagename for title etc. */
    pageNameNice = pageName.substring(0, pageName.length()-4);
    char[] pageNameChar = pageNameNice.toCharArray();
    pageNameChar[0] = Character.toUpperCase(pageNameChar[0]);
    pageNameNice = new String(pageNameChar);
    pageNameNice = pageNameNice.replace('_', ' ');

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <title>Network Monitoring System - ");
 out.print(pageNameNice); 
      out.write("</title>\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"./styles/main.css\" />\n");
      out.write("        \n");
      out.write("        ");
      server.function.CustomCharts CustomCharts = null;
      CustomCharts = (server.function.CustomCharts) _jspx_page_context.getAttribute("CustomCharts", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (CustomCharts == null){
        CustomCharts = new server.function.CustomCharts();
        _jspx_page_context.setAttribute("CustomCharts", CustomCharts, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write(" \n");
      out.write("        ");
 out.print(CustomCharts.importScripts()); 
      out.write("\n");
      out.write("    </head>\n");
      out.write("\n");
      out.write("    <body>\n");
      out.write("        <div id=\"website_container\">\n");
      out.write("            <div id=\"banner\">\n");
      out.write("                <h1 id=\"head\">Network Monitoring System</h1>\n");
      out.write("                <a href=\"./\" class=\"menu_link menu_link_first");
 if("home.jsp".equals(pageName)){out.print(" menu_link_active");} 
      out.write("\">Home</a>\n");
      out.write("                <a href=\"./statistics.jsp\" class=\"menu_link");
 if("statistics.jsp".equals(pageName)){out.print(" menu_link_active");} 
      out.write("\">Statistics</a>\n");
      out.write("                <a href=\"./live_traffic.jsp\" class=\"menu_link");
 if("live_traffic.jsp".equals(pageName)){out.print(" menu_link_active");} 
      out.write("\">Live traffic</a>\n");
      out.write("                <a href=\"./create_user.jsp\" class=\"menu_link");
 if("create_user.jsp".equals(pageName)){out.print(" menu_link_active");} 
      out.write("\">Create user</a>\n");
      out.write("                <a href=\"./login.jsp\" class=\"menu_link");
 if("login.jsp".equals(pageName)){out.print(" menu_link_active");} 
      out.write("\">Login</a>\n");
      out.write("                <a href=\"./control_panel.jsp\" class=\"menu_link");
 if("control_panel.jsp".equals(pageName)){out.print(" menu_link_active");} 
      out.write("\">Control Panel</a>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"main\">\n");
      out.write("                <h2 id=\"title\">");
 out.print(pageNameNice); 
      out.write("</h2>");
      out.write('\n');
      out.write('\n');

    boolean fileExists = false;
    boolean useStdPage = false;
    int i, chartNum = 0;
    String path, savedData;
    String[] temp, layout, selectedCharts;
    
    /* Check if customize-file exists */
    path = application.getRealPath("/") + "customized_charts.txt";
    java.io.File file = new java.io.File(path);
    if(file.exists()) {
        fileExists = true;
    }
    
    /* Check if user wants std. page */
    if("true".equals(request.getParameter("std"))) {
        useStdPage = true;
    }
    
    if (fileExists && !useStdPage) {
        /* Reads from txt-file */
        java.io.BufferedReader reader = new java.io.BufferedReader(new java.io.FileReader(path));
        savedData = reader.readLine();

        /* Insert into arrays */
        temp = savedData.split(";");
        layout = temp[0].split(",");
        selectedCharts = temp[1].split(",");
        
        out.println("This is your custom statistics page. You can always acces the standard page");
        out.println("<a href=\"./statistics.jsp?std=true\">here</a>, or customize your page");
        out.println("<a href=\"./customize_selection.jsp\">here</a>.");
        
        /* Print layout with charts */
        for (i = 0; i < 5; i++) {
            if ("1".equals(layout[i])) {
                out.println("<div class=\"statistics_big\">");
                out.println(CustomCharts.insertChartFromName(selectedCharts[chartNum]));
                out.println("</div>");
                
                chartNum++;
            }
            else if ("2".equals(layout[i])) {
                out.println("<div class=\"statistics_small\">");
                out.println(CustomCharts.insertChartFromName(selectedCharts[chartNum]));
                out.println("</div>");
                
                chartNum++;
                
                out.println("<div class=\"statistics_small\">");
                out.println(CustomCharts.insertChartFromName(selectedCharts[chartNum]));
                out.println("</div>");
                
                chartNum++;
            }
        }
        
        out.println("<div class=\"clear\"></div>");
    }
    else {

      out.write("\n");
      out.write("\n");
      out.write("<div id=\"statistics_top_right\">");
 out.println(CustomCharts.top10Pie1Month()); 
      out.write("</div>\n");
      out.write("This is the main page for network statistics. We have picked out some charts,\n");
      out.write("that we think might interest most of our users. However, if you have a login for\n");
      out.write("our service, it is also possible for you to costomize this page.\n");
      out.write("<br /><br />\n");
      out.write("You can add additional charts, as well as rearrange the entire page.\n");
      out.write("<br /><br />\n");
      out.write("The customization page can be found <a href=\"./customize_selection.jsp\">here.</a>\n");
      out.write("<div class=\"clear\">");
 out.println(CustomCharts.top10Bar1Month()); 
      out.write("</div>\n");
      out.write("\n");

    }

      out.write('\n');
      out.write('\n');
      out.write("            </div>\n");
      out.write("            <div id=\"bottom\">\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </body>\n");
      out.write("\n");
      out.write("</html> ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
